# Generated by Django 3.2.20 on 2023-11-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport_info_aip',
            name='frequencies',
        ),
        migrations.RemoveField(
            model_name='airport_info_aip',
            name='images',
        ),
        migrations.RemoveField(
            model_name='airport_info_aip',
            name='runways',
        ),
    ]
