# Generated by Django 3.2.20 on 2023-09-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude_deg', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude_deg', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation_ft', models.CharField(blank=True, max_length=255, null=True)),
                ('continent', models.CharField(blank=True, max_length=255, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('iso_country', models.CharField(blank=True, max_length=255, null=True)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('iso_region', models.CharField(blank=True, max_length=255, null=True)),
                ('local_region', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_service', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_code', models.CharField(blank=True, max_length=255, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=255, null=True)),
                ('home_link', models.URLField(blank=True, max_length=255, null=True)),
                ('wikipedia_link', models.URLField(blank=True, max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
