# Generated by Django 3.2.20 on 2023-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_airport_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport_Info_AIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('trafficType', models.CharField(max_length=255)),
                ('magneticDeclination', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('geometry', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
                ('elevation', models.FloatField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('referenceDatum', models.CharField(max_length=255)),
                ('ppr', models.BooleanField()),
                ('private', models.BooleanField()),
                ('skydiveActivity', models.BooleanField()),
                ('winchOnly', models.BooleanField()),
                ('runways', models.IntegerField()),
                ('designator', models.CharField(max_length=255)),
                ('trueHeading', models.FloatField()),
                ('alignedTrueNorth', models.FloatField()),
                ('operations', models.CharField(max_length=255)),
                ('mainRunway', models.CharField(max_length=255)),
                ('turnDirection', models.CharField(max_length=255)),
                ('takeOffOnly', models.BooleanField()),
                ('landingOnly', models.BooleanField()),
                ('surface', models.CharField(max_length=255)),
                ('composition', models.CharField(max_length=255)),
                ('mainComposite', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('mtow', models.FloatField()),
                ('dimension', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('declaredDistance', models.FloatField()),
                ('tora', models.FloatField()),
                ('lda', models.FloatField()),
                ('pilotCtrlLighting', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('createdBy', models.CharField(max_length=255)),
                ('updatedBy', models.CharField(max_length=255)),
                ('elevationGeoid', models.FloatField()),
                ('geoidHeight', models.FloatField()),
                ('hae', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='airport_info',
            name='Max_takeoff_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
